# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import agentos_pb2 as protos_dot_agentos__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/agentos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentRegistryServiceStub:
    """--- Agent Registry Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/agentos.AgentRegistryService/RegisterAgent',
                request_serializer=protos_dot_agentos__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/agentos.AgentRegistryService/GetAgent',
                request_serializer=protos_dot_agentos__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.GetAgentResponse.FromString,
                _registered_method=True)


class AgentRegistryServiceServicer:
    """--- Agent Registry Service ---

    """

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=protos_dot_agentos__pb2.RegisterAgentRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=protos_dot_agentos__pb2.GetAgentRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.GetAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.AgentRegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.AgentRegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRegistryService:
    """--- Agent Registry Service ---

    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentRegistryService/RegisterAgent',
            protos_dot_agentos__pb2.RegisterAgentRequest.SerializeToString,
            protos_dot_agentos__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentRegistryService/GetAgent',
            protos_dot_agentos__pb2.GetAgentRequest.SerializeToString,
            protos_dot_agentos__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMGatewayServiceStub:
    """--- LLM Gateway Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCompletion = channel.unary_unary(
                '/agentos.LLMGatewayService/GenerateCompletion',
                request_serializer=protos_dot_agentos__pb2.GenerateCompletionRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.GenerateCompletionResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/agentos.LLMGatewayService/GetEmbedding',
                request_serializer=protos_dot_agentos__pb2.GetEmbeddingRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.GetEmbeddingResponse.FromString,
                _registered_method=True)


class LLMGatewayServiceServicer:
    """--- LLM Gateway Service ---

    """

    def GenerateCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompletion,
                    request_deserializer=protos_dot_agentos__pb2.GenerateCompletionRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.GenerateCompletionResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=protos_dot_agentos__pb2.GetEmbeddingRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.GetEmbeddingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.LLMGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.LLMGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMGatewayService:
    """--- LLM Gateway Service ---

    """

    @staticmethod
    def GenerateCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.LLMGatewayService/GenerateCompletion',
            protos_dot_agentos__pb2.GenerateCompletionRequest.SerializeToString,
            protos_dot_agentos__pb2.GenerateCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.LLMGatewayService/GetEmbedding',
            protos_dot_agentos__pb2.GetEmbeddingRequest.SerializeToString,
            protos_dot_agentos__pb2.GetEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryEngineServiceStub:
    """--- Memory Engine Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveMemory = channel.unary_unary(
                '/agentos.MemoryEngineService/SaveMemory',
                request_serializer=protos_dot_agentos__pb2.SaveMemoryRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/agentos.MemoryEngineService/SearchMemory',
                request_serializer=protos_dot_agentos__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)


class MemoryEngineServiceServicer:
    """--- Memory Engine Service ---

    """

    def SaveMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryEngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMemory,
                    request_deserializer=protos_dot_agentos__pb2.SaveMemoryRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=protos_dot_agentos__pb2.SearchMemoryRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.SearchMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.MemoryEngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.MemoryEngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryEngineService:
    """--- Memory Engine Service ---

    """

    @staticmethod
    def SaveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.MemoryEngineService/SaveMemory',
            protos_dot_agentos__pb2.SaveMemoryRequest.SerializeToString,
            protos_dot_agentos__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.MemoryEngineService/SearchMemory',
            protos_dot_agentos__pb2.SearchMemoryRequest.SerializeToString,
            protos_dot_agentos__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentRuntimeServiceStub:
    """--- Agent Runtime Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/agentos.AgentRuntimeService/ExecuteTask',
                request_serializer=protos_dot_agentos__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=protos_dot_agentos__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)


class AgentRuntimeServiceServicer:
    """--- Agent Runtime Service ---

    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=protos_dot_agentos__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=protos_dot_agentos__pb2.ExecuteTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentos.AgentRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentos.AgentRuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentRuntimeService:
    """--- Agent Runtime Service ---

    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentos.AgentRuntimeService/ExecuteTask',
            protos_dot_agentos__pb2.ExecuteTaskRequest.SerializeToString,
            protos_dot_agentos__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
